### ISSUE TITLE
tag-filter.js is output even for anonymous users

### ISSUE THREAD

**Issue by q2apro** [svivian/q2a-tagging-tools#27]
File `qa-tt-layer.php`

Even if only registered users can ask, the file `tag-filter.js` is read in the head_script() and outputed frontend.

It should check for either qa_is_logged_in() or better: Does user have permission to ask. Only then output the javascript.

PS: And why not load the file directly as script source, but file_get_contents()?

**Comment by svivian** [comment]
Yes it only checks if the points are below the threshold, and any user/anon who is not allowed to ask is counting as below the threshold. The code only appears on the ask page though, so not too much of a problem really.

`file_get_contents` is used because it needs to output custom variables depending on current settings. I suppose those could be inserted directly and then the other script linked up, but doesn't seem much point. Putting it inline also avoids the overhead of an extra HTTP request.

**Comment by q2apro** [comment]
> The code only appears on the ask page though, so not too much of a problem really.

Exactly, and I wanted to have a clean start page :) so I am checking for the user permission now and only then output the code.

**Comment by svivian** [comment]
I've fixed this now in the latest release (1.9). The JS code only appears when a user is able to ask a question.
